### ISSUE TITLE
[BUG] Include/exclude_keys not working with Avro codec output in S3 Sink

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#3163] opened 2023-08-14 23:10 UTC
**Describe the bug**
Specifying include/exclude_keys in the S3 sink with avro schema enabled will ignore the include/exclude_keys when creating entries from the schema:
```
Caused by: java.lang.RuntimeException: The event has a key ('s3') which is not included in the schema.
```

With sink config:
```
        codec:
          avro:
            schema: >
              {
                "type" : "record",
                "namespace" : "org.opensearch.dataprepper.examples",
                "name" : "VpcFlowLog",
                "fields" : [
                  { "name" : "version", "type" : ["null", "string"]},
                  { "name" : "srcport", "type": ["null", "int"]},
                  { "name" : "dstport", "type": ["null", "int"]},
                  { "name" : "accountId", "type" : ["null", "string"]},
                  { "name" : "interfaceId", "type" : ["null", "string"]},
                  { "name" : "srcaddr", "type" : ["null", "string"]},
                  { "name" : "dstaddr", "type" : ["null", "string"]},
                  { "name" : "start", "type": ["null", "int"]},
                  { "name" : "end", "type": ["null", "int"]},
                  { "name" : "protocol", "type": ["null", "int"]},
                  { "name" : "packets", "type": ["null", "int"]},
                  { "name" : "bytes", "type": ["null", "int"]},
                  { "name" : "action", "type": ["null", "string"]},
                  { "name" : "logStatus", "type" : ["null", "string"]}
                ]
              }
        exclude_keys:
          - s3
```

**Comment by dlvenable** [comment] 2023-08-15 01:42
It appears that Avro is failing because the `s3` object is not in the schema. But, it shouldn't have to be since the  `s3` key is marked as excluded.

**Comment by daixba** [comment] 2023-08-15 02:11
I believe the the root cause is as below:

In the sink model, the include/exclude key is append with prefix “/”,  so “s3” in the example will become “/s3”.  This may be not acceptable for some codecs as it only looks for containing keys.   So the fix should be remove the prefix “/” whenever there are checks on whether or not containing keys.  Such as in the `data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodec.java`

```
        for (final String key : eventData.keySet()) {
            if (isExcludeKeyAvailable && config.getExcludeKeys().contains(key)) {
                continue;
            }
            final Schema.Field field = schema.getField(key);
            final Object value = schemaMapper(field, eventData.get(key));
            avroRecord.put(key, value);
        }
        return avroRecord;
```

`config.getExcludeKeys().contains(key)` should be changed to remove the prefix "/".

**Comment by dlvenable** [comment] 2023-08-15 15:00
It seems that the solution for supporting include/exclude keys is somewhat problematic because it perform string comparison rather than using the `Event` class to determine the key. Also, this `eventData` is already a `Map` which is thus disconnected from the `Event` model.

I propose that the initial version of `include_keys`/`exclude_keys` would work only with key names. That is, they will not be JSON Path like many other locations. This can be implemented by adding a restriction to disallow `/` in the names. And the code can be updated to not have the `/` and thus `config.getExcludeKeys().contains(key)`.

@daixba , @kkondaka, @graytaylor0 , @engechas  , Any thoughts on this proposed solution for now?

**Comment by dlvenable** [comment] 2023-08-15 15:06
One possible solution that could help fix this longer-term would be to create an external iterator (often called visitor) on the `Event` model. It could also be supplied with a list of include/exclude fields. In this way, the `Event` itself is iterating over the model. This can allow it properly know which keys to include or exclude. Then the codecs would be responsible for putting the data into the target object. Ideally with this solution, the codecs are not using `.toMap()`.

**Comment by asifsmohammed** [comment] 2023-08-16 18:36
We also remove `/` from key if it ends with `/`, should we also remove that or leave it as it is?
https://github.com/opensearch-project/data-prepper/blob/94d7b1040e641c3ff95bbc515d4dfc55f909bacf/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java#L149

**Comment by dlvenable** [comment] 2023-08-16 19:12
@asifsmohammed , We should remove that line.

Additionally, I think we should validate on start-up that there are no slashes at all. JSON paths are not going to be supported, so there should be no slashes. It should be only a key name.

Thus the following is valid.

```
exclude_keys:
  - s3
  - packets
```

All of these should fail:

```
exclude_keys:
  - /s3
  - packets/
  - s3/key
```

**Closed** 2023-08-18 18:46 UTC
Labels: bug
